/** @type {import('tailwindcss').Config} */
const cv = (name) => `rgb(var(--color-${name}) / <alpha-value>)`

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': cv('surface-dim'),
        tertiary: '#f9f5f5',
        'inverse-primary': '#006970',
        'tertiary-container': '#dcd9d8',
        'on-primary-container': cv('on-primary-container'),
        'error-container': '#93000a',
        'on-surface-variant': cv('on-surface-variant'),
        'on-tertiary-container': cv('on-tertiary-container'),
        error: '#ffb4ab',
        'on-secondary-fixed': '#23005b',
        'tertiary-fixed-dim': '#c9c6c5',
        'on-secondary-fixed-variant': '#5700c9',
        'on-primary': cv('on-primary'),
        'surface-tint': cv('surface-tint'),
        secondary: cv('secondary'),
        'on-tertiary': '#313030',
        surface: cv('surface'),
        'surface-container': cv('surface-container'),
        'outline-variant': cv('outline-variant'),
        'on-surface': cv('on-surface'),
        'surface-container-high': cv('surface-container-high'),
        'primary-fixed': '#7df4ff',
        'on-primary-fixed-variant': '#004f54',
        'on-error-container': '#ffdad6',
        background: cv('background'),
        'surface-container-low': cv('surface-container-low'),
        'surface-container-lowest': cv('surface-container-lowest'),
        'surface-bright': cv('surface-bright'),
        primary: cv('primary'),
        'inverse-on-surface': cv('inverse-on-surface'),
        'primary-container': cv('primary-container'),
        'surface-container-highest': cv('surface-container-highest'),
        'inverse-surface': cv('inverse-surface'),
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary-fixed': '#1c1b1b',
        outline: cv('outline'),
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d1bcff',
        'on-tertiary-fixed-variant': '#474646',
        'primary-fixed-dim': cv('primary-fixed-dim'),
        'on-secondary': '#3c0090',
        'on-error': '#690005',
        'on-primary-fixed': '#002022',
        'surface-variant': cv('surface-variant'),
        'on-secondary-container': '#ddcdff',
        'secondary-container': cv('secondary-container'),
        'on-background': cv('on-background'),
        'text-muted': cv('text-muted'),
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        gutter: '24px',
        'container-max': '1280px',
        unit: '8px',
      },
      fontFamily: {
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'terminal-small': ['"JetBrains Mono"', 'monospace'],
        'code-label': ['"JetBrains Mono"', 'monospace'],
        'body-base': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'terminal-small': ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'code-label': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-base': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
      },
      maxWidth: {
        'container-desktop': '1280px',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
