/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#12131a',
        tertiary: '#f9f5f5',
        'inverse-primary': '#006970',
        'tertiary-container': '#dcd9d8',
        'on-primary-container': '#006970',
        'error-container': '#93000a',
        'on-surface-variant': '#b9cacb',
        'on-tertiary-container': '#605e5e',
        error: '#ffb4ab',
        'on-secondary-fixed': '#23005b',
        'tertiary-fixed-dim': '#c9c6c5',
        'on-secondary-fixed-variant': '#5700c9',
        'on-primary': '#00363a',
        'surface-tint': '#00dbe9',
        secondary: '#d1bcff',
        'on-tertiary': '#313030',
        surface: '#12131a',
        'surface-container': '#1e1f26',
        'outline-variant': '#3b494b',
        'on-surface': '#e2e1eb',
        'surface-container-high': '#282a31',
        'primary-fixed': '#7df4ff',
        'on-primary-fixed-variant': '#004f54',
        'on-error-container': '#ffdad6',
        background: '#12131a',
        'surface-container-low': '#1a1b22',
        'surface-container-lowest': '#0c0e14',
        'surface-bright': '#383940',
        primary: '#dbfcff',
        'inverse-on-surface': '#2f3037',
        'primary-container': '#00f0ff',
        'surface-container-highest': '#33343c',
        'inverse-surface': '#e2e1eb',
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary-fixed': '#1c1b1b',
        outline: '#849495',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d1bcff',
        'on-tertiary-fixed-variant': '#474646',
        'primary-fixed-dim': '#00dbe9',
        'on-secondary': '#3c0090',
        'on-error': '#690005',
        'on-primary-fixed': '#002022',
        'surface-variant': '#33343c',
        'on-secondary-container': '#ddcdff',
        'secondary-container': '#7000ff',
        'on-background': '#e2e1eb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        gutter: '24px',
        'container-max': '1280px',
        unit: '8px',
      },
      fontFamily: {
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'terminal-small': ['"JetBrains Mono"', 'monospace'],
        'code-label': ['"JetBrains Mono"', 'monospace'],
        'body-base': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'terminal-small': ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
        'code-label': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-base': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
      },
      maxWidth: {
        'container-desktop': '1280px',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
